export * from './accountAccess.service';
import { AccountAccessService } from './accountAccess.service';
export * from './accounts.service';
import { AccountsService } from './accounts.service';
export * from './balances.service';
import { BalancesService } from './balances.service';
export * from './beneficiaries.service';
import { BeneficiariesService } from './beneficiaries.service';
export * from './directDebits.service';
import { DirectDebitsService } from './directDebits.service';
export * from './scheduledPayments.service';
import { ScheduledPaymentsService } from './scheduledPayments.service';
export * from './standingOrders.service';
import { StandingOrdersService } from './standingOrders.service';
export * from './statements.service';
import { StatementsService } from './statements.service';
export * from './transactions.service';
import { TransactionsService } from './transactions.service';
export const APIS = [AccountAccessService, AccountsService, BalancesService, BeneficiariesService, DirectDebitsService, ScheduledPaymentsService, StandingOrdersService, StatementsService, TransactionsService];
