/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v1.1.1
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Data3 } from './data3';
import { Links } from './links';
import { Meta } from './meta';


export interface AccountGETResponse {
    Data: Data3;
    Links: Links;
    Meta: Meta;
}
