/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v1.1.1
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Data6Amount } from './data6Amount';
import { Data6CreditLine } from './data6CreditLine';


/**
 * Balance
 */
export interface Balance {
    /**
     * A unique and immutable identifier used to identify the account resource. This identifier has no meaning to the account owner.
     */
    AccountId: string;
    Amount: Data6Amount;
    /**
     * Indicates whether the balance is a credit or a debit balance. Usage: A zero balance is considered to be a credit balance.
     */
    CreditDebitIndicator: Balance.CreditDebitIndicatorEnum;
    /**
     * Balance type, in a coded form.
     */
    Type: Balance.TypeEnum;
    /**
     * Indicates the date (and time) of the balance.  All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     */
    DateTime: Date;
    /**
     * Set of elements used to provide details on the credit line.
     */
    CreditLine?: Array<Data6CreditLine>;
}
export namespace Balance {
    export type CreditDebitIndicatorEnum = 'Credit' | 'Debit';
    export const CreditDebitIndicatorEnum = {
        Credit: 'Credit' as CreditDebitIndicatorEnum,
        Debit: 'Debit' as CreditDebitIndicatorEnum
    }
    export type TypeEnum = 'ClosingAvailable' | 'ClosingBooked' | 'Expected' | 'ForwardAvailable' | 'Information' | 'InterimAvailable' | 'InterimBooked' | 'OpeningAvailable' | 'OpeningBooked' | 'PreviouslyClosedBooked';
    export const TypeEnum = {
        ClosingAvailable: 'ClosingAvailable' as TypeEnum,
        ClosingBooked: 'ClosingBooked' as TypeEnum,
        Expected: 'Expected' as TypeEnum,
        ForwardAvailable: 'ForwardAvailable' as TypeEnum,
        Information: 'Information' as TypeEnum,
        InterimAvailable: 'InterimAvailable' as TypeEnum,
        InterimBooked: 'InterimBooked' as TypeEnum,
        OpeningAvailable: 'OpeningAvailable' as TypeEnum,
        OpeningBooked: 'OpeningBooked' as TypeEnum,
        PreviouslyClosedBooked: 'PreviouslyClosedBooked' as TypeEnum
    }
}
