/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v1.1.1
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ClustersAccountDetails } from './clustersAccountDetails';
import { ClustersAccountFeaturesAndBenefits } from './clustersAccountFeaturesAndBenefits';
import { ClustersAccountTransactions } from './clustersAccountTransactions';
import { ClustersRegularPayments } from './clustersRegularPayments';


export interface Clusters {
    AccountDetails?: ClustersAccountDetails;
    RegularPayments?: ClustersRegularPayments;
    AccountTransactions?: ClustersAccountTransactions;
    AccountFeaturesAndBenefits?: ClustersAccountFeaturesAndBenefits;
}
