/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v1.1.1
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Beneficiary } from './beneficiary';
import { DirectDebit } from './directDebit';
import { PermissionsReadBeneficiariesBasic } from './permissionsReadBeneficiariesBasic';
import { PermissionsReadStandingOrdersBasic } from './permissionsReadStandingOrdersBasic';
import { StandingOrder } from './standingOrder';


/**
 * Your Regular Payments
 */
export interface ClustersRegularPayments {
    ReadBeneficiariesBasic?: PermissionsReadBeneficiariesBasic;
    ReadBeneficiariesDetail?: Beneficiary;
    ReadDirectDebits?: DirectDebit;
    ReadStandingOrdersBasic?: PermissionsReadStandingOrdersBasic;
    ReadStandingOrdersDetail?: StandingOrder;
}
