/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreditInterestTierBandSet } from './creditInterestTierBandSet';


/**
 * Details about the interest that may be payable to the BCA account holders
 */
export interface CreditInterest {
    /**
     * The group of tiers or bands for which credit interest can be applied.
     */
    TierBandSet: Array<CreditInterestTierBandSet>;
}
