/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreditInterestTierBand } from './creditInterestTierBand';


/**
 * The group of tiers or bands for which credit interest can be applied.
 */
export interface CreditInterestTierBandSet {
    /**
     * The methodology of how credit interest is paid/applied. It can be:-  1. Banded Interest rates are banded. i.e. Increasing rate on whole balance as balance increases.  2. Tiered Interest rates are tiered. i.e. increasing rate for each tier as balance increases, but interest paid on tier fixed for that tier and not on whole balance.  3. Whole The same interest rate is applied irrespective of the BCA balance
     */
    TierBandMethod: CreditInterestTierBandSet.TierBandMethodEnum;
    /**
     * Methods of calculating interest
     */
    CalculationMethod?: CreditInterestTierBandSet.CalculationMethodEnum;
    /**
     * Describes whether accrued interest is payable only to the BCA or to another bank account
     */
    Destination: CreditInterestTierBandSet.DestinationEnum;
    /**
     * Optional additional notes to supplement the Tier Band Set details
     */
    Notes?: Array<string>;
    /**
     * Tier Band Details
     */
    TierBand: Array<CreditInterestTierBand>;
}
export namespace CreditInterestTierBandSet {
    export type TierBandMethodEnum = 'Banded' | 'Tiered' | 'Whole';
    export const TierBandMethodEnum = {
        Banded: 'Banded' as TierBandMethodEnum,
        Tiered: 'Tiered' as TierBandMethodEnum,
        Whole: 'Whole' as TierBandMethodEnum
    }
    export type CalculationMethodEnum = 'Compound' | 'SimpleInterest';
    export const CalculationMethodEnum = {
        Compound: 'Compound' as CalculationMethodEnum,
        SimpleInterest: 'SimpleInterest' as CalculationMethodEnum
    }
    export type DestinationEnum = 'PayAway' | 'SelfCredit';
    export const DestinationEnum = {
        PayAway: 'PayAway' as DestinationEnum,
        SelfCredit: 'SelfCredit' as DestinationEnum
    }
}
