/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreditInterest1TierBand } from './creditInterest1TierBand';


/**
 * The group of tiers or bands for which credit interest can be applied.
 */
export interface CreditInterest1TierBandSet {
    /**
     * The methodology of how credit interest is charged. It can be:-  1. Banded Interest rates are banded. i.e. Increasing rate on whole balance as balance increases.  2. Tiered Interest rates are tiered. i.e. increasing rate for each tier as balance increases, but interest paid on tier fixed for that tier and not on whole balance.  3. Whole The same interest rate is applied irrespective of the PCA balance
     */
    TierBandMethod: CreditInterest1TierBandSet.TierBandMethodEnum;
    /**
     * Methods of calculating interest
     */
    CalculationMethod?: CreditInterest1TierBandSet.CalculationMethodEnum;
    /**
     * Describes whether accrued interest is payable only to the PCA or to another bank account
     */
    Destination?: CreditInterest1TierBandSet.DestinationEnum;
    /**
     * Optional additional notes to supplement the Tier Band Set details
     */
    Notes?: Array<string>;
    /**
     * Tier Band Details
     */
    TierBand: Array<CreditInterest1TierBand>;
}
export namespace CreditInterest1TierBandSet {
    export type TierBandMethodEnum = 'Tiered' | 'Whole';
    export const TierBandMethodEnum = {
        Tiered: 'Tiered' as TierBandMethodEnum,
        Whole: 'Whole' as TierBandMethodEnum
    }
    export type CalculationMethodEnum = 'Compound' | 'SimpleInterest';
    export const CalculationMethodEnum = {
        Compound: 'Compound' as CalculationMethodEnum,
        SimpleInterest: 'SimpleInterest' as CalculationMethodEnum
    }
    export type DestinationEnum = 'PayAway' | 'SelfCredit';
    export const DestinationEnum = {
        PayAway: 'PayAway' as DestinationEnum,
        SelfCredit: 'SelfCredit' as DestinationEnum
    }
}
