/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v1.1.1
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Data6Amount1 } from './data6Amount1';


export interface Data6CreditLine {
    /**
     * Indicates whether or not the credit line is included in the balance of the account. Usage: If not present, credit line is not included in the balance amount of the account.
     */
    Included: boolean;
    Amount?: Data6Amount1;
    /**
     * Limit type, in a coded form.
     */
    Type?: Data6CreditLine.TypeEnum;
}
export namespace Data6CreditLine {
    export type TypeEnum = 'Pre-Agreed' | 'Emergency' | 'Temporary';
    export const TypeEnum = {
        PreAgreed: 'Pre-Agreed' as TypeEnum,
        Emergency: 'Emergency' as TypeEnum,
        Temporary: 'Temporary' as TypeEnum
    }
}
