/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v1.1.1
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Data4BalanceAmount } from './data4BalanceAmount';


/**
 * Set of elements used to define the balance as a numerical representation of the net increases and decreases in an account after a transaction entry is applied to the account.
 */
export interface Data4Balance {
    Amount: Data4BalanceAmount;
    /**
     * Indicates whether the balance is a credit or a debit balance. Usage: A zero balance is considered to be a credit balance.
     */
    CreditDebitIndicator: Data4Balance.CreditDebitIndicatorEnum;
    /**
     * Balance type, in a coded form.
     */
    Type: Data4Balance.TypeEnum;
}
export namespace Data4Balance {
    export type CreditDebitIndicatorEnum = 'Credit' | 'Debit';
    export const CreditDebitIndicatorEnum = {
        Credit: 'Credit' as CreditDebitIndicatorEnum,
        Debit: 'Debit' as CreditDebitIndicatorEnum
    }
    export type TypeEnum = 'ClosingAvailable' | 'ClosingBooked' | 'Expected' | 'ForwardAvailable' | 'Information' | 'InterimAvailable' | 'InterimBooked' | 'OpeningAvailable' | 'OpeningBooked' | 'PreviouslyClosedBooked';
    export const TypeEnum = {
        ClosingAvailable: 'ClosingAvailable' as TypeEnum,
        ClosingBooked: 'ClosingBooked' as TypeEnum,
        Expected: 'Expected' as TypeEnum,
        ForwardAvailable: 'ForwardAvailable' as TypeEnum,
        Information: 'Information' as TypeEnum,
        InterimAvailable: 'InterimAvailable' as TypeEnum,
        InterimBooked: 'InterimBooked' as TypeEnum,
        OpeningAvailable: 'OpeningAvailable' as TypeEnum,
        OpeningBooked: 'OpeningBooked' as TypeEnum,
        PreviouslyClosedBooked: 'PreviouslyClosedBooked' as TypeEnum
    }
}
