/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v1.1.1
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Set of elements used to fully identify the type of underlying transaction resulting in an entry.
 */
export interface Data4BankTransactionCode {
    /**
     * Specifies the family within a domain.
     */
    Code: string;
    /**
     * Specifies the sub-product family within a specific family.
     */
    SubCode: string;
}
