/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v1.1.1
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Provides the details to identify the beneficiary account.
 */
export interface Data8CreditorAccount {
    /**
     * Name of the identification scheme, in a coded form as published in an external list.
     */
    SchemeName: Data8CreditorAccount.SchemeNameEnum;
    /**
     * Identification assigned by an institution to identify an account. This identification is known by the account owner.
     */
    Identification: string;
    /**
     * Name of the account, as assigned by the account servicing institution, in agreement with the account owner in order to provide an additional means of identification of the account. Usage: The account name is different from the account owner name. The account name is used in certain user communities to provide a means of identifying the account, in addition to the account owner's identity and the account number.
     */
    Name?: string;
    /**
     * This is secondary identification of the account, as assigned by the account servicing institution.  This can be used by building societies to additionally identify accounts with a roll number (in addition to a sort code and account number combination).
     */
    SecondaryIdentification?: string;
}
export namespace Data8CreditorAccount {
    export type SchemeNameEnum = 'IBAN' | 'BBAN';
    export const SchemeNameEnum = {
        IBAN: 'IBAN' as SchemeNameEnum,
        BBAN: 'BBAN' as SchemeNameEnum
    }
}
