/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v1.1.1
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Data4Transaction } from './data4Transaction';


/**
 * Data
 */
export interface Data4 {
    /**
     * Transaction
     */
    Transaction?: Array<Data4Transaction>;
}
