/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v1.1.1
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Data7PreviousPaymentAmount } from './data7PreviousPaymentAmount';


/**
 * Direct Debit
 */
export interface DirectDebit {
    /**
     * A unique and immutable identifier used to identify the account resource. This identifier has no meaning to the account owner.
     */
    AccountId: string;
    /**
     * A unique and immutable identifier used to identify the direct debit resource. This identifier has no meaning to the account owner.
     */
    DirectDebitId?: string;
    /**
     * Direct Debit reference. For AUDDIS service users provide Core Reference. For non AUDDIS service users provide Core reference if possible or last used reference.
     */
    MandateIdentification: string;
    /**
     * Specifies the status of the direct debit in code form.
     */
    DirectDebitStatusCode?: DirectDebit.DirectDebitStatusCodeEnum;
    /**
     * Name of Service User
     */
    Name: string;
    /**
     * Date of most recent direct debit collection.  All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     */
    PreviousPaymentDateTime?: Date;
    PreviousPaymentAmount?: Data7PreviousPaymentAmount;
}
export namespace DirectDebit {
    export type DirectDebitStatusCodeEnum = 'Active' | 'Inactive';
    export const DirectDebitStatusCodeEnum = {
        Active: 'Active' as DirectDebitStatusCodeEnum,
        Inactive: 'Inactive' as DirectDebitStatusCodeEnum
    }
}
