/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Range or amounts or rates for which the fee/charge applies
 */
export interface FeeApplicableRange {
    /**
     * Minimum Amount on which fee/charge is applicable (where it is expressed as an amount)
     */
    MinimumAmount?: string;
    /**
     * Maximum Amount on which fee is applicable (where it is expressed as an amount)
     */
    MaximumAmount?: string;
    /**
     * Minimum rate on which fee/charge is applicable(where it is expressed as an rate)
     */
    MinimumRate?: string;
    /**
     * Maximum rate on which fee/charge is applicable(where it is expressed as an rate)
     */
    MaximumRate?: string;
}
