/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Balance type, in a coded form.
 */
export type OBBalanceType1Code = 'ClosingAvailable' | 'ClosingBooked' | 'ClosingCleared' | 'Expected' | 'ForwardAvailable' | 'Information' | 'InterimAvailable' | 'InterimBooked' | 'InterimCleared' | 'OpeningAvailable' | 'OpeningBooked' | 'OpeningCleared' | 'PreviouslyClosedBooked';

export const OBBalanceType1Code = {
    ClosingAvailable: 'ClosingAvailable' as OBBalanceType1Code,
    ClosingBooked: 'ClosingBooked' as OBBalanceType1Code,
    ClosingCleared: 'ClosingCleared' as OBBalanceType1Code,
    Expected: 'Expected' as OBBalanceType1Code,
    ForwardAvailable: 'ForwardAvailable' as OBBalanceType1Code,
    Information: 'Information' as OBBalanceType1Code,
    InterimAvailable: 'InterimAvailable' as OBBalanceType1Code,
    InterimBooked: 'InterimBooked' as OBBalanceType1Code,
    InterimCleared: 'InterimCleared' as OBBalanceType1Code,
    OpeningAvailable: 'OpeningAvailable' as OBBalanceType1Code,
    OpeningBooked: 'OpeningBooked' as OBBalanceType1Code,
    OpeningCleared: 'OpeningCleared' as OBBalanceType1Code,
    PreviouslyClosedBooked: 'PreviouslyClosedBooked' as OBBalanceType1Code
}
