/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OBBCAData1FeeChargeCap } from './oBBCAData1FeeChargeCap';
import { OBBCAData1FeeChargeDetail } from './oBBCAData1FeeChargeDetail';
import { OtherTariffType } from './otherTariffType';


/**
 * Contains details of fees and charges which are not associated with either Overdraft or features/benefits
 */
export interface OBBCAData1OtherFeesCharges {
    /**
     * TariffType which defines the fee and charges.
     */
    TariffType?: OBBCAData1OtherFeesCharges.TariffTypeEnum;
    /**
     * Name of the tariff
     */
    TariffName?: string;
    OtherTariffType?: OtherTariffType;
    /**
     * Other fees/charges details
     */
    FeeChargeDetail: Array<OBBCAData1FeeChargeDetail>;
    /**
     * Details about any caps (maximum charges) that apply to a particular or group of fee/charge
     */
    FeeChargeCap?: Array<OBBCAData1FeeChargeCap>;
}
export namespace OBBCAData1OtherFeesCharges {
    export type TariffTypeEnum = 'Electronic' | 'Mixed' | 'Other';
    export const TariffTypeEnum = {
        Electronic: 'Electronic' as TariffTypeEnum,
        Mixed: 'Mixed' as TariffTypeEnum,
        Other: 'Other' as TariffTypeEnum
    }
}
