/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreditInterest } from './creditInterest';
import { OBBCAData1OtherFeesCharges } from './oBBCAData1OtherFeesCharges';
import { Overdraft } from './overdraft';
import { ProductDetails } from './productDetails';


export interface OBBCAData1 {
    ProductDetails?: ProductDetails;
    CreditInterest?: CreditInterest;
    Overdraft?: Overdraft;
    /**
     * Contains details of fees and charges which are not associated with either Overdraft or features/benefits
     */
    OtherFeesCharges?: Array<OBBCAData1OtherFeesCharges>;
}
