/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OBExternalFinancialInstitutionIdentification4Code } from './oBExternalFinancialInstitutionIdentification4Code';
import { OBPostalAddress6 } from './oBPostalAddress6';


/**
 * Financial institution servicing an account for the debtor.
 */
export interface OBBranchAndFinancialInstitutionIdentification6 {
    SchemeName?: OBExternalFinancialInstitutionIdentification4Code;
    /**
     * Unique and unambiguous identification of a financial institution or a branch of a financial institution.
     */
    Identification?: string;
    /**
     * Name by which an agent is known and which is usually used to identify that agent.
     */
    Name?: string;
    PostalAddress?: OBPostalAddress6;
}
