/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountId } from './accountId';
import { OBActiveOrHistoricCurrencyAndAmount } from './oBActiveOrHistoricCurrencyAndAmount';
import { OBBalanceType1Code } from './oBBalanceType1Code';
import { OBCreditLine1 } from './oBCreditLine1';


/**
 * Set of elements used to define the balance details.
 */
export interface OBCashBalance1 {
    AccountId: AccountId;
    /**
     * Indicates whether the balance is a credit or a debit balance.  Usage: A zero balance is considered to be a credit balance.
     */
    CreditDebitIndicator: OBCashBalance1.CreditDebitIndicatorEnum;
    Type: OBBalanceType1Code;
    /**
     * Indicates the date (and time) of the balance. All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     */
    DateTime: Date;
    Amount: OBActiveOrHistoricCurrencyAndAmount;
    /**
     * Set of elements used to provide details on the credit line.
     */
    CreditLine?: Array<OBCreditLine1>;
}
export namespace OBCashBalance1 {
    export type CreditDebitIndicatorEnum = 'Credit' | 'Debit';
    export const CreditDebitIndicatorEnum = {
        Credit: 'Credit' as CreditDebitIndicatorEnum,
        Debit: 'Debit' as CreditDebitIndicatorEnum
    }
}
