/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type OBCreditDebitCode = 'Credit' | 'Debit';

export const OBCreditDebitCode = {
    Credit: 'Credit' as OBCreditDebitCode,
    Debit: 'Debit' as OBCreditDebitCode
}
