/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OBActiveOrHistoricCurrencyAndAmount } from './oBActiveOrHistoricCurrencyAndAmount';
import { OBExternalLimitType1Code } from './oBExternalLimitType1Code';


/**
 * Set of elements used to provide details on the credit line.
 */
export interface OBCreditLine1 {
    /**
     * Indicates whether or not the credit line is included in the balance of the account. Usage: If not present, credit line is not included in the balance amount of the account.
     */
    Included: boolean;
    Type?: OBExternalLimitType1Code;
    Amount?: OBActiveOrHistoricCurrencyAndAmount;
}
