/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OBActiveOrHistoricCurrencyAndAmount } from './oBActiveOrHistoricCurrencyAndAmount';


/**
 * Set of elements used to provide details on the currency exchange.
 */
export interface OBCurrencyExchange5 {
    /**
     * Currency from which an amount is to be converted in a currency conversion.
     */
    SourceCurrency: string;
    /**
     * Currency from which an amount is to be converted in a currency conversion.
     */
    TargetCurrency?: string;
    /**
     * Currency from which an amount is to be converted in a currency conversion.
     */
    UnitCurrency?: string;
    /**
     * Factor used to convert an amount from one currency into another. This reflects the price at which one currency was bought with another currency. Usage: ExchangeRate expresses the ratio between UnitCurrency and QuotedCurrency (ExchangeRate = UnitCurrency/QuotedCurrency).
     */
    ExchangeRate: number;
    /**
     * Unique identification to unambiguously identify the foreign exchange contract.
     */
    ContractIdentification?: string;
    /**
     * Date and time at which an exchange rate is quoted. All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     */
    QuotationDate?: Date;
    InstructedAmount?: OBActiveOrHistoricCurrencyAndAmount;
}
