/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountId } from './accountId';
import { OBActiveOrHistoricCurrencyAndAmount } from './oBActiveOrHistoricCurrencyAndAmount';
import { OBExternalDirectDebitStatus1Code } from './oBExternalDirectDebitStatus1Code';


/**
 * Account to or from which a cash entry is made.
 */
export interface OBDirectDebit1 {
    AccountId: AccountId;
    /**
     * A unique and immutable identifier used to identify the direct debit resource. This identifier has no meaning to the account owner.
     */
    DirectDebitId?: string;
    /**
     * Direct Debit reference. For AUDDIS service users provide Core Reference. For non AUDDIS service users provide Core reference if possible or last used reference.
     */
    MandateIdentification: string;
    DirectDebitStatusCode?: OBExternalDirectDebitStatus1Code;
    /**
     * Name of Service User.
     */
    Name: string;
    /**
     * Date of most recent direct debit collection. All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     */
    PreviousPaymentDateTime?: Date;
    PreviousPaymentAmount?: OBActiveOrHistoricCurrencyAndAmount;
}
