/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Status of a transaction entry on the books of the account servicer.
 */
export type OBEntryStatus1Code = 'Booked' | 'Pending';

export const OBEntryStatus1Code = {
    Booked: 'Booked' as OBEntryStatus1Code,
    Pending: 'Pending' as OBEntryStatus1Code
}
