/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Specifies the type of account (personal or business).
 */
export type OBExternalAccountType1Code = 'Business' | 'Personal';

export const OBExternalAccountType1Code = {
    Business: 'Business' as OBExternalAccountType1Code,
    Personal: 'Personal' as OBExternalAccountType1Code
}
