/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Statement type, in a coded form.
 */
export type OBExternalStatementType1Code = 'AccountClosure' | 'AccountOpening' | 'Annual' | 'Interim' | 'RegularPeriodic';

export const OBExternalStatementType1Code = {
    AccountClosure: 'AccountClosure' as OBExternalStatementType1Code,
    AccountOpening: 'AccountOpening' as OBExternalStatementType1Code,
    Annual: 'Annual' as OBExternalStatementType1Code,
    Interim: 'Interim' as OBExternalStatementType1Code,
    RegularPeriodic: 'RegularPeriodic' as OBExternalStatementType1Code
}
