/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Specifies the status of the standing order in code form.
 */
export type OBExternalStandingOrderStatus1Code = 'Active' | 'Inactive';

export const OBExternalStandingOrderStatus1Code = {
    Active: 'Active' as OBExternalStandingOrderStatus1Code,
    Inactive: 'Inactive' as OBExternalStandingOrderStatus1Code
}
