/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * The card authorisation type.
 */
export type OBExternalCardAuthorisationType1Code = 'ConsumerDevice' | 'Contactless' | 'None' | 'PIN';

export const OBExternalCardAuthorisationType1Code = {
    ConsumerDevice: 'ConsumerDevice' as OBExternalCardAuthorisationType1Code,
    Contactless: 'Contactless' as OBExternalCardAuthorisationType1Code,
    None: 'None' as OBExternalCardAuthorisationType1Code,
    PIN: 'PIN' as OBExternalCardAuthorisationType1Code
}
