/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Descriptive code for the product category.  If ProductType - \"Other\" is chosen, the object OtherProductType must be populated with name, and description.
 */
export type OBExternalProductType1Code = 'BusinessCurrentAccount' | 'CommercialCreditCard' | 'Other' | 'PersonalCurrentAccount' | 'SMELoan';

export const OBExternalProductType1Code = {
    BusinessCurrentAccount: 'BusinessCurrentAccount' as OBExternalProductType1Code,
    CommercialCreditCard: 'CommercialCreditCard' as OBExternalProductType1Code,
    Other: 'Other' as OBExternalProductType1Code,
    PersonalCurrentAccount: 'PersonalCurrentAccount' as OBExternalProductType1Code,
    SMELoan: 'SMELoan' as OBExternalProductType1Code
}
