/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Name of the card scheme.
 */
export type OBExternalCardSchemeType1Code = 'AmericanExpress' | 'Diners' | 'Discover' | 'MasterCard' | 'VISA';

export const OBExternalCardSchemeType1Code = {
    AmericanExpress: 'AmericanExpress' as OBExternalCardSchemeType1Code,
    Diners: 'Diners' as OBExternalCardSchemeType1Code,
    Discover: 'Discover' as OBExternalCardSchemeType1Code,
    MasterCard: 'MasterCard' as OBExternalCardSchemeType1Code,
    VISA: 'VISA' as OBExternalCardSchemeType1Code
}
