/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Limit type, in a coded form.
 */
export type OBExternalLimitType1Code = 'Available' | 'Credit' | 'Emergency' | 'Pre-Agreed' | 'Temporary';

export const OBExternalLimitType1Code = {
    Available: 'Available' as OBExternalLimitType1Code,
    Credit: 'Credit' as OBExternalLimitType1Code,
    Emergency: 'Emergency' as OBExternalLimitType1Code,
    PreAgreed: 'Pre-Agreed' as OBExternalLimitType1Code,
    Temporary: 'Temporary' as OBExternalLimitType1Code
}
