/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Specifies the status of consent resource in code form.
 */
export type OBExternalRequestStatus1Code = 'Authorised' | 'AwaitingAuthorisation' | 'Rejected' | 'Revoked';

export const OBExternalRequestStatus1Code = {
    Authorised: 'Authorised' as OBExternalRequestStatus1Code,
    AwaitingAuthorisation: 'AwaitingAuthorisation' as OBExternalRequestStatus1Code,
    Rejected: 'Rejected' as OBExternalRequestStatus1Code,
    Revoked: 'Revoked' as OBExternalRequestStatus1Code
}
