/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Offer type, in a coded form.
 */
export type OBExternalOfferType1Code = 'BalanceTransfer' | 'LimitIncrease' | 'MoneyTransfer' | 'Other' | 'PromotionalRate';

export const OBExternalOfferType1Code = {
    BalanceTransfer: 'BalanceTransfer' as OBExternalOfferType1Code,
    LimitIncrease: 'LimitIncrease' as OBExternalOfferType1Code,
    MoneyTransfer: 'MoneyTransfer' as OBExternalOfferType1Code,
    Other: 'Other' as OBExternalOfferType1Code,
    PromotionalRate: 'PromotionalRate' as OBExternalOfferType1Code
}
