/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Specifies the Open Banking account access data types. This is a list of the data clusters being consented by the PSU, and requested for authorisation with the ASPSP.
 */
export type OBExternalPermissions1Code = 'ReadAccountsBasic' | 'ReadAccountsDetail' | 'ReadBalances' | 'ReadBeneficiariesBasic' | 'ReadBeneficiariesDetail' | 'ReadDirectDebits' | 'ReadOffers' | 'ReadPAN' | 'ReadParty' | 'ReadPartyPSU' | 'ReadProducts' | 'ReadScheduledPaymentsBasic' | 'ReadScheduledPaymentsDetail' | 'ReadStandingOrdersBasic' | 'ReadStandingOrdersDetail' | 'ReadStatementsBasic' | 'ReadStatementsDetail' | 'ReadTransactionsBasic' | 'ReadTransactionsCredits' | 'ReadTransactionsDebits' | 'ReadTransactionsDetail';

export const OBExternalPermissions1Code = {
    ReadAccountsBasic: 'ReadAccountsBasic' as OBExternalPermissions1Code,
    ReadAccountsDetail: 'ReadAccountsDetail' as OBExternalPermissions1Code,
    ReadBalances: 'ReadBalances' as OBExternalPermissions1Code,
    ReadBeneficiariesBasic: 'ReadBeneficiariesBasic' as OBExternalPermissions1Code,
    ReadBeneficiariesDetail: 'ReadBeneficiariesDetail' as OBExternalPermissions1Code,
    ReadDirectDebits: 'ReadDirectDebits' as OBExternalPermissions1Code,
    ReadOffers: 'ReadOffers' as OBExternalPermissions1Code,
    ReadPAN: 'ReadPAN' as OBExternalPermissions1Code,
    ReadParty: 'ReadParty' as OBExternalPermissions1Code,
    ReadPartyPSU: 'ReadPartyPSU' as OBExternalPermissions1Code,
    ReadProducts: 'ReadProducts' as OBExternalPermissions1Code,
    ReadScheduledPaymentsBasic: 'ReadScheduledPaymentsBasic' as OBExternalPermissions1Code,
    ReadScheduledPaymentsDetail: 'ReadScheduledPaymentsDetail' as OBExternalPermissions1Code,
    ReadStandingOrdersBasic: 'ReadStandingOrdersBasic' as OBExternalPermissions1Code,
    ReadStandingOrdersDetail: 'ReadStandingOrdersDetail' as OBExternalPermissions1Code,
    ReadStatementsBasic: 'ReadStatementsBasic' as OBExternalPermissions1Code,
    ReadStatementsDetail: 'ReadStatementsDetail' as OBExternalPermissions1Code,
    ReadTransactionsBasic: 'ReadTransactionsBasic' as OBExternalPermissions1Code,
    ReadTransactionsCredits: 'ReadTransactionsCredits' as OBExternalPermissions1Code,
    ReadTransactionsDebits: 'ReadTransactionsDebits' as OBExternalPermissions1Code,
    ReadTransactionsDetail: 'ReadTransactionsDetail' as OBExternalPermissions1Code
}
