/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Party type, in a coded form.
 */
export type OBExternalPartyType1Code = 'Delegate' | 'Joint' | 'Sole';

export const OBExternalPartyType1Code = {
    Delegate: 'Delegate' as OBExternalPartyType1Code,
    Joint: 'Joint' as OBExternalPartyType1Code,
    Sole: 'Sole' as OBExternalPartyType1Code
}
