/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Specifies the sub type of account (product family group).
 */
export type OBExternalAccountSubType1Code = 'ChargeCard' | 'CreditCard' | 'CurrentAccount' | 'EMoney' | 'Loan' | 'Mortgage' | 'PrePaidCard' | 'Savings';

export const OBExternalAccountSubType1Code = {
    ChargeCard: 'ChargeCard' as OBExternalAccountSubType1Code,
    CreditCard: 'CreditCard' as OBExternalAccountSubType1Code,
    CurrentAccount: 'CurrentAccount' as OBExternalAccountSubType1Code,
    EMoney: 'EMoney' as OBExternalAccountSubType1Code,
    Loan: 'Loan' as OBExternalAccountSubType1Code,
    Mortgage: 'Mortgage' as OBExternalAccountSubType1Code,
    PrePaidCard: 'PrePaidCard' as OBExternalAccountSubType1Code,
    Savings: 'Savings' as OBExternalAccountSubType1Code
}
