/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OBExternalPartyType1Code } from './oBExternalPartyType1Code';
import { OBPostalAddress8 } from './oBPostalAddress8';


export interface OBParty1 {
    /**
     * A unique and immutable identifier used to identify the customer resource. This identifier has no meaning to the account owner.
     */
    PartyId: string;
    /**
     * Number assigned by an agent to identify its customer.
     */
    PartyNumber?: string;
    PartyType?: OBExternalPartyType1Code;
    /**
     * Name by which a party is known and which is usually used to identify that party.
     */
    Name?: string;
    /**
     * Address for electronic mail (e-mail).
     */
    EmailAddress?: string;
    /**
     * Collection of information that identifies a phone number, as defined by telecom services.
     */
    Phone?: string;
    /**
     * Collection of information that identifies a mobile phone number, as defined by telecom services.
     */
    Mobile?: string;
    /**
     * Postal address of a party.
     */
    Address?: Array<OBPostalAddress8>;
}
