/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreditInterest1 } from './creditInterest1';
import { OtherFeesCharges } from './otherFeesCharges';
import { Overdraft1 } from './overdraft1';
import { ProductDetails1 } from './productDetails1';


export interface OBPCAData1 {
    ProductDetails?: ProductDetails1;
    CreditInterest?: CreditInterest1;
    Overdraft?: Overdraft1;
    OtherFeesCharges?: OtherFeesCharges;
}
