/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OBReadData1 } from './oBReadData1';
import { OBRisk2 } from './oBRisk2';


export interface OBReadConsent1 {
    Data: OBReadData1;
    Risk: OBRisk2;
}
