/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OBStatement1 } from './oBStatement1';


export interface OBReadStatement1Data {
    /**
     * Provides further details on a statement resource.
     */
    Statement?: Array<OBStatement1>;
}
