/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Links } from './links';
import { Meta } from './meta';
import { OBReadConsentResponse1Data } from './oBReadConsentResponse1Data';
import { OBRisk2 } from './oBRisk2';


export interface OBReadConsentResponse1 {
    Data: OBReadConsentResponse1Data;
    Risk: OBRisk2;
    Links: Links;
    Meta: Meta;
}
