/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OBTransaction4 } from './oBTransaction4';


export interface OBReadTransaction4Data {
    /**
     * Provides further details on an entry in the report.
     */
    Transaction?: Array<OBTransaction4>;
}
