/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OBExternalStatementDateTimeType1Code } from './oBExternalStatementDateTimeType1Code';


/**
 * Set of elements used to provide details of a generic date time for the statement resource.
 */
export interface OBStatementDateTime1 {
    /**
     * Date and time associated with the date time type. All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     */
    DateTime: Date;
    Type: OBExternalStatementDateTimeType1Code;
}
