/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OBExternalCardAuthorisationType1Code } from './oBExternalCardAuthorisationType1Code';
import { OBExternalCardSchemeType1Code } from './oBExternalCardSchemeType1Code';


/**
 * Set of elements to describe the card instrument used in the transaction.
 */
export interface OBTransactionCardInstrument1 {
    CardSchemeName: OBExternalCardSchemeType1Code;
    AuthorisationType?: OBExternalCardAuthorisationType1Code;
    /**
     * Name of the cardholder using the card instrument.
     */
    Name?: string;
    /**
     * Identification assigned by an institution to identify the card instrument used in the transaction. This identification is known by the account owner, and may be masked.
     */
    Identification?: string;
}
