/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountId } from './accountId';
import { OBActiveOrHistoricCurrencyAndAmount } from './oBActiveOrHistoricCurrencyAndAmount';
import { OBBankTransactionCodeStructure1 } from './oBBankTransactionCodeStructure1';
import { OBBranchAndFinancialInstitutionIdentification6 } from './oBBranchAndFinancialInstitutionIdentification6';
import { OBCashAccount6 } from './oBCashAccount6';
import { OBCurrencyExchange5 } from './oBCurrencyExchange5';
import { OBEntryStatus1Code } from './oBEntryStatus1Code';
import { OBMerchantDetails1 } from './oBMerchantDetails1';
import { OBSupplementaryData1 } from './oBSupplementaryData1';
import { OBTransaction4ProprietaryBankTransactionCode } from './oBTransaction4ProprietaryBankTransactionCode';
import { OBTransactionCardInstrument1 } from './oBTransactionCardInstrument1';
import { OBTransactionCashBalance } from './oBTransactionCashBalance';
import { TransactionInformation } from './transactionInformation';


/**
 * Provides further details on an entry in the report.
 */
export interface OBTransaction4Detail {
    AccountId: AccountId;
    /**
     * Unique identifier for the transaction within an servicing institution. This identifier is both unique and immutable.
     */
    TransactionId?: string;
    /**
     * Unique reference for the transaction. This reference is optionally populated, and may as an example be the FPID in the Faster Payments context.
     */
    TransactionReference?: string;
    /**
     * Unique reference for the statement. This reference may be optionally populated if available.
     */
    StatementReference?: Array<string>;
    /**
     * Indicates whether the transaction is a credit or a debit entry.
     */
    CreditDebitIndicator: OBTransaction4Detail.CreditDebitIndicatorEnum;
    Status: OBEntryStatus1Code;
    /**
     * Date and time when a transaction entry is posted to an account on the account servicer's books. Usage: Booking date is the expected booking date, unless the status is booked, in which case it is the actual booking date. All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     */
    BookingDateTime: Date;
    /**
     * Date and time at which assets become available to the account owner in case of a credit entry, or cease to be available to the account owner in case of a debit transaction entry. Usage: If transaction entry status is pending and value date is present, then the value date refers to an expected/requested value date. For transaction entries subject to availability/float and for which availability information is provided, the value date must not be used. In this case the availability component identifies the number of availability days. All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     */
    ValueDateTime?: Date;
    /**
     * Information that locates and identifies a specific address for a transaction entry, that is presented in free format text.
     */
    AddressLine?: string;
    Amount: OBActiveOrHistoricCurrencyAndAmount;
    ChargeAmount?: OBActiveOrHistoricCurrencyAndAmount;
    CurrencyExchange?: OBCurrencyExchange5;
    BankTransactionCode?: OBBankTransactionCodeStructure1;
    ProprietaryBankTransactionCode?: OBTransaction4ProprietaryBankTransactionCode;
    CardInstrument?: OBTransactionCardInstrument1;
    SupplementaryData?: OBSupplementaryData1;
    TransactionInformation?: TransactionInformation;
    Balance?: OBTransactionCashBalance;
    MerchantDetails?: OBMerchantDetails1;
    CreditorAgent?: OBBranchAndFinancialInstitutionIdentification6;
    CreditorAccount?: OBCashAccount6;
    DebtorAgent?: OBBranchAndFinancialInstitutionIdentification6;
    DebtorAccount?: OBCashAccount6;
}
export namespace OBTransaction4Detail {
    export type CreditDebitIndicatorEnum = 'Credit' | 'Debit';
    export const CreditDebitIndicatorEnum = {
        Credit: 'Credit' as CreditDebitIndicatorEnum,
        Debit: 'Debit' as CreditDebitIndicatorEnum
    }
}
