/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Set of elements to fully identify a proprietary bank transaction code.
 */
export interface OBTransaction4ProprietaryBankTransactionCode {
    /**
     * Proprietary bank transaction code to identify the underlying transaction.
     */
    Code: string;
    /**
     * Identification of the issuer of the proprietary bank transaction code.
     */
    Issuer?: string;
}
