/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OverdraftOtherFeeType } from './overdraftOtherFeeType';


/**
 * Details about any caps (maximum charges) that apply to a particular fee/charge
 */
export interface OtherFeesChargesFeeChargeCap {
    /**
     * Fee/charge type which is being capped
     */
    FeeType: Array<OtherFeesChargesFeeChargeCap.FeeTypeEnum>;
    /**
     * Indicates that this is the minimum/ maximum fee/charge that can be applied by the financial institution
     */
    MinMaxType: OtherFeesChargesFeeChargeCap.MinMaxTypeEnum;
    /**
     * fee/charges are captured dependent on the number of occurrences rather than capped at a particular amount
     */
    FeeCapOccurrence?: number;
    /**
     * Cap amount charged for a fee/charge (where it is charged in terms of an amount rather than a rate)
     */
    FeeCapAmount?: string;
    /**
     * Period e.g. day, week, month etc. for which the fee/charge is capped
     */
    CappingPeriod?: OtherFeesChargesFeeChargeCap.CappingPeriodEnum;
    /**
     * Free text for adding  extra details for fee charge cap
     */
    Notes?: Array<string>;
    /**
     * Other fee type code which is not available in the standard code set
     */
    OtherFeeType?: Array<OverdraftOtherFeeType>;
}
export namespace OtherFeesChargesFeeChargeCap {
    export type FeeTypeEnum = 'ServiceCAccountFee' | 'ServiceCAccountFeeMonthly' | 'ServiceCOther' | 'Other';
    export const FeeTypeEnum = {
        ServiceCAccountFee: 'ServiceCAccountFee' as FeeTypeEnum,
        ServiceCAccountFeeMonthly: 'ServiceCAccountFeeMonthly' as FeeTypeEnum,
        ServiceCOther: 'ServiceCOther' as FeeTypeEnum,
        Other: 'Other' as FeeTypeEnum
    }
    export type MinMaxTypeEnum = 'Minimum' | 'Maximum';
    export const MinMaxTypeEnum = {
        Minimum: 'Minimum' as MinMaxTypeEnum,
        Maximum: 'Maximum' as MinMaxTypeEnum
    }
    export type CappingPeriodEnum = 'AcademicTerm' | 'Day' | 'Half Year' | 'Month' | 'Quarter' | 'Week' | 'Year';
    export const CappingPeriodEnum = {
        AcademicTerm: 'AcademicTerm' as CappingPeriodEnum,
        Day: 'Day' as CappingPeriodEnum,
        HalfYear: 'Half Year' as CappingPeriodEnum,
        Month: 'Month' as CappingPeriodEnum,
        Quarter: 'Quarter' as CappingPeriodEnum,
        Week: 'Week' as CappingPeriodEnum,
        Year: 'Year' as CappingPeriodEnum
    }
}
