/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OtherFeesChargesFeeChargeCap } from './otherFeesChargesFeeChargeCap';
import { OtherFeesChargesFeeChargeDetail } from './otherFeesChargesFeeChargeDetail';


/**
 * Contains details of fees and charges which are not associated with either borrowing or features/benefits
 */
export interface OtherFeesCharges {
    /**
     * Other fees/charges details
     */
    FeeChargeDetail: Array<OtherFeesChargesFeeChargeDetail>;
    /**
     * Details about any caps (maximum charges) that apply to a particular fee/charge
     */
    FeeChargeCap?: Array<OtherFeesChargesFeeChargeCap>;
}
