/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FeeApplicableRange } from './feeApplicableRange';
import { OtherApplicationFrequency1 } from './otherApplicationFrequency1';
import { OtherCalculationFrequency1 } from './otherCalculationFrequency1';
import { OtherFeeCategoryType } from './otherFeeCategoryType';
import { OtherFeeRateType1 } from './otherFeeRateType1';
import { OtherFeeType1 } from './otherFeeType1';
import { OtherFeesChargesFeeChargeCap } from './otherFeesChargesFeeChargeCap';


/**
 * Other fees/charges details
 */
export interface OtherFeesChargesFeeChargeDetail {
    /**
     * Categorisation of fees and charges into standard categories.
     */
    FeeCategory: OtherFeesChargesFeeChargeDetail.FeeCategoryEnum;
    /**
     * Fee/Charge Type
     */
    FeeType: OtherFeesChargesFeeChargeDetail.FeeTypeEnum;
    /**
     * Fee Amount charged for a fee/charge (where it is charged in terms of an amount rather than a rate)
     */
    FeeAmount?: string;
    /**
     * Rate charged for Fee/Charge (where it is charged in terms of a rate rather than an amount)
     */
    FeeRate?: string;
    /**
     * Rate type for Fee/Charge (where it is charged in terms of a rate rather than an amount)
     */
    FeeRateType?: OtherFeesChargesFeeChargeDetail.FeeRateTypeEnum;
    /**
     * How frequently the fee/charge is applied to the account
     */
    ApplicationFrequency: OtherFeesChargesFeeChargeDetail.ApplicationFrequencyEnum;
    /**
     * How frequently the fee/charge is calculated
     */
    CalculationFrequency?: OtherFeesChargesFeeChargeDetail.CalculationFrequencyEnum;
    /**
     * Optional additional notes to supplement the fee/charge details.
     */
    Notes?: Array<string>;
    OtherFeeCategoryType?: OtherFeeCategoryType;
    OtherFeeType?: OtherFeeType1;
    OtherFeeRateType?: OtherFeeRateType1;
    OtherApplicationFrequency?: OtherApplicationFrequency1;
    OtherCalculationFrequency?: OtherCalculationFrequency1;
    /**
     * Details about any caps (maximum charges) that apply to a particular fee/charge
     */
    FeeChargeCap?: Array<OtherFeesChargesFeeChargeCap>;
    FeeApplicableRange?: FeeApplicableRange;
}
export namespace OtherFeesChargesFeeChargeDetail {
    export type FeeCategoryEnum = 'Other' | 'Servicing';
    export const FeeCategoryEnum = {
        Other: 'Other' as FeeCategoryEnum,
        Servicing: 'Servicing' as FeeCategoryEnum
    }
    export type FeeTypeEnum = 'ServiceCAccountFee' | 'ServiceCAccountFeeMonthly' | 'ServiceCOther' | 'Other';
    export const FeeTypeEnum = {
        ServiceCAccountFee: 'ServiceCAccountFee' as FeeTypeEnum,
        ServiceCAccountFeeMonthly: 'ServiceCAccountFeeMonthly' as FeeTypeEnum,
        ServiceCOther: 'ServiceCOther' as FeeTypeEnum,
        Other: 'Other' as FeeTypeEnum
    }
    export type FeeRateTypeEnum = 'LinkedBaseRate' | 'Gross' | 'Net' | 'Other';
    export const FeeRateTypeEnum = {
        LinkedBaseRate: 'LinkedBaseRate' as FeeRateTypeEnum,
        Gross: 'Gross' as FeeRateTypeEnum,
        Net: 'Net' as FeeRateTypeEnum,
        Other: 'Other' as FeeRateTypeEnum
    }
    export type ApplicationFrequencyEnum = 'AccountClosing' | 'AccountOpening' | 'AcademicTerm' | 'ChargingPeriod' | 'Daily' | 'PerItem' | 'Monthly' | 'OnAccountAnniversary' | 'Other' | 'PerHour' | 'PerOccurrence' | 'PerSheet' | 'PerTransaction' | 'PerTransactionAmount' | 'PerTransactionPercentage' | 'Quarterly' | 'SixMonthly' | 'StatementMonthly' | 'Weekly' | 'Yearly';
    export const ApplicationFrequencyEnum = {
        AccountClosing: 'AccountClosing' as ApplicationFrequencyEnum,
        AccountOpening: 'AccountOpening' as ApplicationFrequencyEnum,
        AcademicTerm: 'AcademicTerm' as ApplicationFrequencyEnum,
        ChargingPeriod: 'ChargingPeriod' as ApplicationFrequencyEnum,
        Daily: 'Daily' as ApplicationFrequencyEnum,
        PerItem: 'PerItem' as ApplicationFrequencyEnum,
        Monthly: 'Monthly' as ApplicationFrequencyEnum,
        OnAccountAnniversary: 'OnAccountAnniversary' as ApplicationFrequencyEnum,
        Other: 'Other' as ApplicationFrequencyEnum,
        PerHour: 'PerHour' as ApplicationFrequencyEnum,
        PerOccurrence: 'PerOccurrence' as ApplicationFrequencyEnum,
        PerSheet: 'PerSheet' as ApplicationFrequencyEnum,
        PerTransaction: 'PerTransaction' as ApplicationFrequencyEnum,
        PerTransactionAmount: 'PerTransactionAmount' as ApplicationFrequencyEnum,
        PerTransactionPercentage: 'PerTransactionPercentage' as ApplicationFrequencyEnum,
        Quarterly: 'Quarterly' as ApplicationFrequencyEnum,
        SixMonthly: 'SixMonthly' as ApplicationFrequencyEnum,
        StatementMonthly: 'StatementMonthly' as ApplicationFrequencyEnum,
        Weekly: 'Weekly' as ApplicationFrequencyEnum,
        Yearly: 'Yearly' as ApplicationFrequencyEnum
    }
    export type CalculationFrequencyEnum = 'AccountClosing' | 'AccountOpening' | 'AcademicTerm' | 'ChargingPeriod' | 'Daily' | 'PerItem' | 'Monthly' | 'OnAccountAnniversary' | 'Other' | 'PerHour' | 'PerOccurrence' | 'PerSheet' | 'PerTransaction' | 'PerTransactionAmount' | 'PerTransactionPercentage' | 'Quarterly' | 'SixMonthly' | 'StatementMonthly' | 'Weekly' | 'Yearly';
    export const CalculationFrequencyEnum = {
        AccountClosing: 'AccountClosing' as CalculationFrequencyEnum,
        AccountOpening: 'AccountOpening' as CalculationFrequencyEnum,
        AcademicTerm: 'AcademicTerm' as CalculationFrequencyEnum,
        ChargingPeriod: 'ChargingPeriod' as CalculationFrequencyEnum,
        Daily: 'Daily' as CalculationFrequencyEnum,
        PerItem: 'PerItem' as CalculationFrequencyEnum,
        Monthly: 'Monthly' as CalculationFrequencyEnum,
        OnAccountAnniversary: 'OnAccountAnniversary' as CalculationFrequencyEnum,
        Other: 'Other' as CalculationFrequencyEnum,
        PerHour: 'PerHour' as CalculationFrequencyEnum,
        PerOccurrence: 'PerOccurrence' as CalculationFrequencyEnum,
        PerSheet: 'PerSheet' as CalculationFrequencyEnum,
        PerTransaction: 'PerTransaction' as CalculationFrequencyEnum,
        PerTransactionAmount: 'PerTransactionAmount' as CalculationFrequencyEnum,
        PerTransactionPercentage: 'PerTransactionPercentage' as CalculationFrequencyEnum,
        Quarterly: 'Quarterly' as CalculationFrequencyEnum,
        SixMonthly: 'SixMonthly' as CalculationFrequencyEnum,
        StatementMonthly: 'StatementMonthly' as CalculationFrequencyEnum,
        Weekly: 'Weekly' as CalculationFrequencyEnum,
        Yearly: 'Yearly' as CalculationFrequencyEnum
    }
}
