/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OverdraftOverdraftFeesCharges1 } from './overdraftOverdraftFeesCharges1';
import { OverdraftOverdraftTierBand } from './overdraftOverdraftTierBand';


/**
 * Tier band set details
 */
export interface OverdraftOverdraftTierBandSet {
    /**
     * The methodology of how overdraft is charged. It can be: 'Whole'  Where the same charge/rate is applied to the entirety of the overdraft balance (where charges are applicable).  'Tiered' Where different charges/rates are applied dependent on overdraft maximum and minimum balance amount tiers defined by the lending financial organisation 'Banded' Where different charges/rates are applied dependent on overdraft maximum and minimum balance amount bands defined by a government organisation.
     */
    TierBandMethod: OverdraftOverdraftTierBandSet.TierBandMethodEnum;
    /**
     * An overdraft can either be 'committed' which means that the facility cannot be withdrawn without reasonable notification before it's agreed end date, or 'on demand' which means that the financial institution can demand repayment at any point in time.
     */
    OverdraftType?: OverdraftOverdraftTierBandSet.OverdraftTypeEnum;
    /**
     * Unique and unambiguous identification of a  Tier Band for a overdraft product.
     */
    Identification?: string;
    /**
     * Indicates if the Overdraft is authorised (Y) or unauthorised (N)
     */
    AuthorisedIndicator?: boolean;
    /**
     * When a customer exceeds their credit limit, a financial institution will not charge the customer unauthorised overdraft charges if they do not exceed by more than the buffer amount. Note: Authorised overdraft charges may still apply.
     */
    BufferAmount?: string;
    /**
     * Optional additional notes to supplement the overdraft Tier Band Set details
     */
    Notes?: Array<string>;
    /**
     * Provides overdraft details for a specific tier or band
     */
    OverdraftTierBand: Array<OverdraftOverdraftTierBand>;
    /**
     * Overdraft fees and charges details
     */
    OverdraftFeesCharges?: Array<OverdraftOverdraftFeesCharges1>;
}
export namespace OverdraftOverdraftTierBandSet {
    export type TierBandMethodEnum = 'Banded' | 'Tiered' | 'Whole';
    export const TierBandMethodEnum = {
        Banded: 'Banded' as TierBandMethodEnum,
        Tiered: 'Tiered' as TierBandMethodEnum,
        Whole: 'Whole' as TierBandMethodEnum
    }
    export type OverdraftTypeEnum = 'Committed' | 'OnDemand';
    export const OverdraftTypeEnum = {
        Committed: 'Committed' as OverdraftTypeEnum,
        OnDemand: 'OnDemand' as OverdraftTypeEnum
    }
}
