/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Overdraft1OverdraftTierBandSet } from './overdraft1OverdraftTierBandSet';


/**
 * Details about Overdraft rates, fees & charges
 */
export interface Overdraft1 {
    /**
     * Associated Notes about the overdraft rates
     */
    Notes?: Array<string>;
    /**
     * Tier band set details
     */
    OverdraftTierBandSet: Array<Overdraft1OverdraftTierBandSet>;
}
