/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OverdraftOverdraftFeesCharges } from './overdraftOverdraftFeesCharges';


/**
 * Provides overdraft details for a specific tier or band
 */
export interface OverdraftOverdraftTierBand {
    /**
     * Unique and unambiguous identification of a  Tier Band for a overdraft.
     */
    Identification?: string;
    /**
     * Minimum value of Overdraft Tier/Band
     */
    TierValueMin: string;
    /**
     * Maximum value of Overdraft Tier/Band
     */
    TierValueMax?: string;
    /**
     * EAR means Effective Annual Rate and/or Equivalent Annual Rate (frequently used interchangeably), being the actual annual interest rate of an Overdraft.
     */
    EAR?: string;
    /**
     * Specifies the minimum length of a band for a fixed overdraft agreement
     */
    AgreementLengthMin?: number;
    /**
     * Specifies the maximum length of a band for a fixed overdraft agreement
     */
    AgreementLengthMax?: number;
    /**
     * Specifies the period of a fixed length overdraft agreement
     */
    AgreementPeriod?: OverdraftOverdraftTierBand.AgreementPeriodEnum;
    /**
     * Refers to which interest rate is applied when interests are tiered. For example, if an overdraft balance is £2k and the interest tiers are:- 0-£500 0.1%, 500-1000 0.2%, 1000-10000 0.5%, then the applicable interest rate could either be 0.5% of the entire balance (since the account balance sits in the top interest tier) or (0.1%*500)+(0.2%*500)+(0.5%*1000). In the 1st situation, we say the interest is applied to the ‘Whole’ of the account balance,  and in the 2nd that it is ‘Tiered’.
     */
    OverdraftInterestChargingCoverage?: OverdraftOverdraftTierBand.OverdraftInterestChargingCoverageEnum;
    /**
     * Indicates whether the advertised overdraft rate is guaranteed to be offered to a borrower by the bank e.g. if it’s part of a government scheme, or whether the rate may vary dependent on the applicant’s circumstances.
     */
    BankGuaranteedIndicator?: boolean;
    /**
     * Optional additional notes to supplement the Tier/band details
     */
    Notes?: Array<string>;
    /**
     * Overdraft fees and charges
     */
    OverdraftFeesCharges?: Array<OverdraftOverdraftFeesCharges>;
}
export namespace OverdraftOverdraftTierBand {
    export type AgreementPeriodEnum = 'Day' | 'Half Year' | 'Month' | 'Quarter' | 'Week' | 'Year';
    export const AgreementPeriodEnum = {
        Day: 'Day' as AgreementPeriodEnum,
        HalfYear: 'Half Year' as AgreementPeriodEnum,
        Month: 'Month' as AgreementPeriodEnum,
        Quarter: 'Quarter' as AgreementPeriodEnum,
        Week: 'Week' as AgreementPeriodEnum,
        Year: 'Year' as AgreementPeriodEnum
    }
    export type OverdraftInterestChargingCoverageEnum = 'Banded' | 'Tiered' | 'Whole';
    export const OverdraftInterestChargingCoverageEnum = {
        Banded: 'Banded' as OverdraftInterestChargingCoverageEnum,
        Tiered: 'Tiered' as OverdraftInterestChargingCoverageEnum,
        Whole: 'Whole' as OverdraftInterestChargingCoverageEnum
    }
}
