/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Overdraft1OverdraftFeeChargeCap } from './overdraft1OverdraftFeeChargeCap';
import { Overdraft1OverdraftFeeChargeDetail } from './overdraft1OverdraftFeeChargeDetail';


/**
 * Overdraft fees and charges
 */
export interface Overdraft1OverdraftFeesCharges {
    /**
     * Details about any caps (maximum charges) that apply to a particular fee/charge
     */
    OverdraftFeeChargeCap?: Array<Overdraft1OverdraftFeeChargeCap>;
    /**
     * Details about the fees/charges
     */
    OverdraftFeeChargeDetail: Array<Overdraft1OverdraftFeeChargeDetail>;
}
