/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OverdraftOverdraftFeeChargeCap } from './overdraftOverdraftFeeChargeCap';
import { OverdraftOverdraftFeeChargeDetail } from './overdraftOverdraftFeeChargeDetail';


/**
 * Overdraft fees and charges
 */
export interface OverdraftOverdraftFeesCharges {
    /**
     * Details about any caps (maximum charges) that apply to a particular fee/charge. Capping can either be based on an amount (in gbp), an amount (in items) or a rate.
     */
    OverdraftFeeChargeCap?: Array<OverdraftOverdraftFeeChargeCap>;
    /**
     * Details about the fees/charges
     */
    OverdraftFeeChargeDetail: Array<OverdraftOverdraftFeeChargeDetail>;
}
