/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Overdraft1OverdraftFeesCharges } from './overdraft1OverdraftFeesCharges';


/**
 * Provides overdraft details for a specific tier or band
 */
export interface Overdraft1OverdraftTierBand {
    /**
     * Unique and unambiguous identification of a  Tier Band for a overdraft.
     */
    Identification?: string;
    /**
     * Minimum value of Overdraft Tier/Band
     */
    TierValueMin: string;
    /**
     * Maximum value of Overdraft Tier/Band
     */
    TierValueMax?: string;
    /**
     * Interest charged on whole amount or tiered/banded
     */
    OverdraftInterestChargingCoverage?: Overdraft1OverdraftTierBand.OverdraftInterestChargingCoverageEnum;
    /**
     * Indicates that a bank provides the overdraft limit up to TierValueMIn to all customers automatically
     */
    BankGuaranteedIndicator?: boolean;
    /**
     * EAR means Effective Annual Rate and/or Equivalent Annual Rate (frequently used interchangeably), being the actual annual interest rate of an Overdraft.
     */
    EAR?: string;
    /**
     * Optional additional notes to supplement the Tier/band details
     */
    Notes?: Array<string>;
    /**
     * Overdraft fees and charges
     */
    OverdraftFeesCharges?: Array<Overdraft1OverdraftFeesCharges>;
}
export namespace Overdraft1OverdraftTierBand {
    export type OverdraftInterestChargingCoverageEnum = 'Tiered' | 'Whole';
    export const OverdraftInterestChargingCoverageEnum = {
        Tiered: 'Tiered' as OverdraftInterestChargingCoverageEnum,
        Whole: 'Whole' as OverdraftInterestChargingCoverageEnum
    }
}
