/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v1.1.1
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Account } from './account';
import { Balance } from './balance';
import { Beneficiary } from './beneficiary';
import { Data4Transaction } from './data4Transaction';
import { DirectDebit } from './directDebit';
import { PermissionsReadAccountsBasic } from './permissionsReadAccountsBasic';
import { PermissionsReadBeneficiariesBasic } from './permissionsReadBeneficiariesBasic';
import { PermissionsReadStandingOrdersBasic } from './permissionsReadStandingOrdersBasic';
import { PermissionsReadTransactionsBasic } from './permissionsReadTransactionsBasic';
import { Product } from './product';
import { StandingOrder } from './standingOrder';


export interface Permissions {
    ReadAccountsBasic?: PermissionsReadAccountsBasic;
    ReadAccountsDetail?: Account;
    ReadBalances?: Balance;
    ReadBeneficiariesBasic?: PermissionsReadBeneficiariesBasic;
    ReadBeneficiariesDetail?: Beneficiary;
    ReadDirectDebits?: DirectDebit;
    ReadProducts?: Product;
    ReadStandingOrdersBasic?: PermissionsReadStandingOrdersBasic;
    ReadStandingOrdersDetail?: StandingOrder;
    ReadTransactionsBasic?: PermissionsReadTransactionsBasic;
    ReadTransactionsDetail?: Data4Transaction;
}
