/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ProductDetails1 {
    /**
     * Market segmentation is a marketing term referring to the aggregating of prospective buyers into groups, or segments, that have common needs and respond similarly to a marketing action. Market segmentation enables companies to target different categories of consumers who perceive the full value of certain products and services differently from one another.  Read more: Market Segmentation http://www.investopedia.com/terms/m/marketsegmentation.asp#ixzz4gfEEalTd  With respect to PCA products, they are segmented in relation to different markets that they wish to focus on. 
     */
    Segment?: Array<ProductDetails1.SegmentEnum>;
    /**
     * The maximum relevant charges that could accrue as defined fully in Part 7 of the CMA order
     */
    MonthlyMaximumCharge?: string;
    /**
     * Optional additional notes to supplement the Core product details
     */
    Notes?: Array<string>;
}
export namespace ProductDetails1 {
    export type SegmentEnum = 'Basic' | 'BenefitAndReward' | 'CreditInterest' | 'Cashback' | 'General' | 'Graduate' | 'Other' | 'Overdraft' | 'Packaged' | 'Premium' | 'Reward' | 'Student' | 'YoungAdult' | 'Youth';
    export const SegmentEnum = {
        Basic: 'Basic' as SegmentEnum,
        BenefitAndReward: 'BenefitAndReward' as SegmentEnum,
        CreditInterest: 'CreditInterest' as SegmentEnum,
        Cashback: 'Cashback' as SegmentEnum,
        General: 'General' as SegmentEnum,
        Graduate: 'Graduate' as SegmentEnum,
        Other: 'Other' as SegmentEnum,
        Overdraft: 'Overdraft' as SegmentEnum,
        Packaged: 'Packaged' as SegmentEnum,
        Premium: 'Premium' as SegmentEnum,
        Reward: 'Reward' as SegmentEnum,
        Student: 'Student' as SegmentEnum,
        YoungAdult: 'YoungAdult' as SegmentEnum,
        Youth: 'Youth' as SegmentEnum
    }
}
