/**
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ProductDetails {
    /**
     * Market segmentation is a marketing term referring to the aggregating of prospective buyers into groups, or segments, that have common needs and respond similarly to a marketing action. Market segmentation enables companies to target different categories of consumers who perceive the full value of certain products and services differently from one another.  Read more: Market Segmentation http://www.investopedia.com/terms/m/marketsegmentation.asp#ixzz4gfEEalTd  With respect to BCA products, they are segmented in relation to different markets that they wish to focus on. 
     */
    Segment?: Array<ProductDetails.SegmentEnum>;
    /**
     * The length/duration of the fee free period
     */
    FeeFreeLength?: number;
    /**
     * The unit of period (days, weeks, months etc.) of the promotional length
     */
    FeeFreeLengthPeriod?: ProductDetails.FeeFreeLengthPeriodEnum;
    /**
     * Optional additional notes to supplement the Core product details
     */
    Notes?: Array<string>;
}
export namespace ProductDetails {
    export type SegmentEnum = 'ClientAccount' | 'Standard' | 'NonCommercialChaitiesClbSoc' | 'NonCommercialPublicAuthGovt' | 'Religious' | 'SectorSpecific' | 'Startup' | 'Switcher';
    export const SegmentEnum = {
        ClientAccount: 'ClientAccount' as SegmentEnum,
        Standard: 'Standard' as SegmentEnum,
        NonCommercialChaitiesClbSoc: 'NonCommercialChaitiesClbSoc' as SegmentEnum,
        NonCommercialPublicAuthGovt: 'NonCommercialPublicAuthGovt' as SegmentEnum,
        Religious: 'Religious' as SegmentEnum,
        SectorSpecific: 'SectorSpecific' as SegmentEnum,
        Startup: 'Startup' as SegmentEnum,
        Switcher: 'Switcher' as SegmentEnum
    }
    export type FeeFreeLengthPeriodEnum = 'Day' | 'Half Year' | 'Month' | 'Quarter' | 'Week' | 'Year';
    export const FeeFreeLengthPeriodEnum = {
        Day: 'Day' as FeeFreeLengthPeriodEnum,
        HalfYear: 'Half Year' as FeeFreeLengthPeriodEnum,
        Month: 'Month' as FeeFreeLengthPeriodEnum,
        Quarter: 'Quarter' as FeeFreeLengthPeriodEnum,
        Week: 'Week' as FeeFreeLengthPeriodEnum,
        Year: 'Year' as FeeFreeLengthPeriodEnum
    }
}
